### ISSUE TITLE
Inbound connections fail with "AttributeError: 'Session' object has no attribute 'address'"

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1175]
* Trinity version: v0.1.0-alpha.28

### What is wrong?

It appears all inbound connections fail with:
```
   ERROR  09-18 23:44:08            FullServer  Unexpected error handling handshake
Traceback (most recent call last):
  ...
AttributeError: 'Session' object has no attribute 'address'

```

### How can it be fixed

This is already fixed by #1129, in master. I just added the issue so people who run into the error can find out more.

Also worth noting that this wasn't discovered during prerelease smoke tests because the network didn't allow any incoming connections (No UPnP available), so the code path didn't get triggered.

**Comment by pipermerriam** [comment]
This functionality is covered by tests in the new pool manager api introduced in #966

Sent from ProtonMail mobile

-------- Original Message --------
