### PR TITLE
Add host attribute to NoopMetricsRegistry

### LINKED ISSUE #2055: AttributeError: 'NoopMetricsRegistry' object has no attribute 'host'
```
<bound method AsyncioIsolatedComponent._do_run of <trinity.components.builtin.syncer.component.SyncerComponent object at 0x7f550ddb0970>> raised an unexpected exception
Traceback (most recent call last):
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 205, in run_process
    runner(async_fn, args, to_parent)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 168, in _run_on_asyncio
    result: Any = loop.run_until_complete(_do_async_fn(async_fn, args, to_parent, loop))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 160, in _do_async_fn
    return await async_fn_task
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 85, in _handle_coro
    return await coro_task
  File "/home/salgado/src/snakecharmers/trinity/trinity/extensibility/asyncio.py", line 79, in _do_run
    await wait_first(
  File "/home/salgado/src/snakecharmers/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 391, in do_run
    await wait_first(tasks, max_wait_after_cancellation=2)
  File "/home/salgado/src/snakecharmers/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 399, in launch_sync
    await strategy.sync(
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 232, in sync
    await manager.wait_finished()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 441, in background_asyncio_service
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/beam/service.py", line 60, in run
    await self._pivot_loop()
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/beam/service.py", line 80, in _pivot_loop
    await self.sync_metrics_registry.record_pivot(latest_block)
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/metrics/sync_metrics_registry.py", line 21, in record_pivot
    f'events title="beam pivot @ block {block_number}",'
AttributeError: 'NoopMetricsRegistry' object has no attribute 'host'
```

I guess this was introduced in 0b83cc16a8daab9832b2fd2157b2b1f4f02e7c5f, @njgheorghita ?

### PR DESCRIPTION
**Pull request by njgheorghita**
### What was wrong?
Fixes #2055 

### How was it fixed?
Added a `host` attribute to the `NoopMetricsRegistry` to fix beam sync crashing when running without metrics enabled.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Clean up commit history

[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/trinity/blob/master/newsfragments/README.md)

[//]: # (See: https://trinity-client.readthedocs.io/en/latest/contributing.html#pull-requests)
- [ ] Add entry to the [release notes](https://github.com/ethereum/trinity/blob/master/newsfragments/README.md)

#### Cute Animal Picture
image

### CODE REVIEW

File: trinity/components/builtin/metrics/sync_metrics_registry.py [hunk 1]
```diff
@@ -9,7 +9,8 @@ class SyncMetricsRegistry:
     """
     Registry to track weighted moving average of pivot events, and report to InfluxDB.
     """
-    def __init__(self, metrics_service: MetricsServiceAPI) -> None:
+    def __init__(self, metrics_service: MetricsServiceAPI, host: str) -> None:
+        self.host = host
```
Comment (njgheorghita) [inline trinity/components/builtin/metrics/sync_metrics_registry.py:13]: > I think this should get the host passed as a str instead of drilling into the registry.

@cburgdorf I'm not sure I understand why? The bug can be fixed by just adding a `host` attribute onto the `NoopMetricsRegistry`. What's the motivation for passing in a `host: str` argument to the `SyncMetricsRegistry`?

Comment (cburgdorf) [reply trinity/components/builtin/metrics/sync_metrics_registry.py:13]: Actually, you are right in the sense that passing in `host` as a `str` here doesn't necessarily matter. The real question actually is: Why are we hitting that error here with the `NoopMetricsRegistry` if the metrics are disabled. We aren't supposed to be hitting `record_pivot` in that case.

```
<bound method AsyncioIsolatedComponent._do_run of <trinity.components.builtin.syncer.component.SyncerComponent object at 0x7f550ddb0970>> raised an unexpected exception
Traceback (most recent call last):
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 205, in run_process
    runner(async_fn, args, to_parent)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 168, in _run_on_asyncio
    result: Any = loop.run_until_complete(_do_async_fn(async_fn, args, to_parent, loop))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 160, in _do_async_fn
    return await async_fn_task
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/asyncio_run_in_process/_child.py", line 85, in _handle_coro
    return await coro_task
  File "/home/salgado/src/snakecharmers/trinity/trinity/extensibility/asyncio.py", line 79, in _do_run
    await wait_first(
  File "/home/salgado/src/snakecharmers/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 391, in do_run
    await wait_first(tasks, max_wait_after_cancellation=2)
  File "/home/salgado/src/snakecharmers/trinity/p2p/asyncio_utils.py", line 69, in wait_first
    raise done_task.exception()
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 399, in launch_sync
    await strategy.sync(
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/syncer/component.py", line 232, in sync
    await manager.wait_finished()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 441, in background_asyncio_service
    raise MultiError(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/beam/service.py", line 60, in run
    await self._pivot_loop()
  File "/home/salgado/src/snakecharmers/trinity/trinity/sync/beam/service.py", line 80, in _pivot_loop
    await self.sync_metrics_registry.record_pivot(latest_block)
  File "/home/salgado/src/snakecharmers/trinity/trinity/components/builtin/metrics/sync_metrics_registry.py", line 21, in record_pivot
    f'events title="beam pivot @ block {block_number}",'
AttributeError: 'NoopMetricsRegistry' object has no attribute 'host' 
```

So my urge to not put the `host` on the `NoopMetricsRegistry` come from the thought that it should not be needed.

Comment (njgheorghita) [reply trinity/components/builtin/metrics/sync_metrics_registry.py]: Ahh, yes exactly! The problem was in the sync service, we pivot if the `sync_metrics_registry` is `None` - however, what was happening was a `sync_metrics_registry` was being created and passed to the service with a `NoopMetricsRegistry` without metrics enabled.

**Review by cburgdorf — APPROVED** [review]
