### ISSUE TITLE
Crash: module 'snappy' has no attribute 'CompressedLengthError'

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1691]
Trinity crashes with

### What is wrong?

```
   DEBUG  2020-04-22 15:39:22,882               Manager  <Manager[ETHPeerPool] flags=SRcfe>: task Connection-<Session <Node(0x745a50@3.0.234.98)> fae02ec9-e13f-4369-ad52-9d87624840e1>[daemon=False] exited with error: module 'snappy' has no attribute 'CompressedLengthError'
Traceback (most recent call last):
  File "/home/jcarver/code/trinity/p2p/multiplexer.py", line 304, in multiplex
    yield
  File "/home/jcarver/code/trinity/p2p/connection.py", line 139, in run
    await self.manager.wait_finished()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/asyncio.py", line 251, in wait_finished
    await self._finished.wait()
  File "/usr/lib/python3.6/asyncio/locks.py", line 283, in wait
    yield from fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/base.py", line 166, in run
    await self.child_manager.run()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/asyncio.py", line 217, in run
    for _, exc_value, exc_tb in self._errors
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/jcarver/code/trinity/p2p/connection.py", line 139, in run
    await self.manager.wait_finished()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/jcarver/code/trinity/p2p/multiplexer.py", line 347, in multiplex
    fut.result()
  File "/home/jcarver/code/trinity/p2p/multiplexer.py", line 366, in _do_multiplexing
    await self._handle_commands(msg_stream, stop)
  File "/home/jcarver/code/trinity/p2p/multiplexer.py", line 383, in _handle_commands
    async for protocol, cmd in msg_stream:
  File "/home/jcarver/code/trinity/p2p/multiplexer.py", line 87, in stream_transport_messages
    except (rlp.exceptions.DeserializationError, snappy.CompressedLengthError) as err:
AttributeError: module 'snappy' has no attribute 'CompressedLengthError'
```

### How can it be fixed

~~Maybe need a different constraint on the snappy library?~~

:man_shrugging:

**Comment by carver** [comment]
Hm, AFAICT, this is not an exception that is exported by python-snappy...

**Comment by carver** [comment]
I updated to the latest: v0.5.4

Still:
```
$ ipython
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import snappy                                                                                                                                                                                                                         

In [2]: snappy.CompressedLengthError                                                                                                                                                                                                          
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-d7e6ac29a5a2> in <module>
----> 1 snappy.CompressedLengthError

AttributeError: module 'snappy' has no attribute 'CompressedLengthError'

In [3]:                                                            
```

**Comment by carver** [comment]
Looks like it was introduced in #1606 

@cburgdorf do you get the same thing at the console as I do above?

This is pretty regularly causing my trinity instance to crash.

**Comment by cburgdorf** [comment]
Mmmh...ok this is weird. I remember I had gotten the same error that Piper reported in #1582 which lead to #1606.

But I can confirm now that accessing `snappy.CompressedLengthError` also results in an `AttributeError` als I haven't seen that error during testing yet.

I also have just recently updated my OS to a newer version so chances are my underlying system snappy library has changed.

Now that I googled around a bit I found this snippet in @pipermerriam 's `py-snappy` (not the one trinity uses)

https://github.com/ethereum/py-snappy/blob/f91082fa1498ed919ef26bd853a4552675c9665a/tests/core/test_libsnappy_compat.py#L10-L13

```python
try:
    from snappy._snappy import CompressedLengthError
except ImportError:
    CompressedLengthError = None
```

I read that as evidence that the underlying OS snappy library may have this or not depending on the specific version, no?

Maybe we need to put in something like that, too?

**Comment by carver** [comment]
Interesting. Even when I install the lowest permitted snappy (0.5.3), that import works for me:

```
$ ipython
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from snappy._snappy import CompressedLengthError                                                                                                                                                                                      

In [2]: CompressedLengthError                                                                                                                                                                                                                 
Out[2]: snappy.CompressedLengthError
```

So maybe we just need:
```diff
-except (rlp.exceptions.DeserializationError, snappy.CompressedLengthError) as err:
+except (rlp.exceptions.DeserializationError, snappy._snappy.CompressedLengthError) as err:
```

**Comment by carver** [comment]
Oh, but of course it depends on the underlying C library version, instead of the python wrapper version.

**Comment by carver** [comment]
So yeah, maybe we need that. I can post a PR shortly.
